### ISSUE TITLE
Pokedex goes to 275

### ISSUE THREAD

**Issue by Ryan-Myers** [huderlem/pokepinball-generations#7]
![image](https://user-images.githubusercontent.com/828639/74269626-c2e9c000-4cd7-11ea-91c2-471c6bf3196c.png)

**Comment by huderlem** [comment]
This is because I had started adding species for Gen 3.  See `constants/pokemon_constants.asm`:

```
	...
	const NUZLEAF     ; $112
	const SHIFTRY     ; $113

NUM_POKEMON EQU 275
```

**Comment by Ryan-Myers** [comment]
What would be your preference for how to handle this? I'm thinking it's best to remove the Gen 3 'mons until there's support for catching them. Would you prefer to make a branch that contains the Gen 3 guys, and remove them from master, or a branch that just focuses on Gen 1/2?

**Comment by huderlem** [comment]
I'd rather keep it how it is for now.  Latest `master` isn't really meant to be the correct playable experience.  That's what the release patches are.
